### ISSUE TITLE
php captcha solver

### ISSUE THREAD

**Issue by RNTL** [akarthik10/Captcha2Text#1]
Hi,

I'm trying to use the php captch_solver ... with not much success. wonder if you can help .. 
1. where do I input the captcha URL ?
2. there is no commented 154 line in hasherv2.php

Thanks.

**Comment by akarthik10** [comment]
Oops, saw this late. Very late. Sorry about that. 
First, there is a piece of code that says uncommen this part when building database. You can use that. 
Second, this assumes you already have your image readily available. If not, you'll have to download it using PHP Curl and store it in captcha.jpg
